name: reddit_video_downloader
description: A new Flutter package which can download videos from reddit. Currently only supports Android, iOS and MacOS
issue_tracker: https://github.com/KathirvelChandrasekaran/reddit_video_downloader/issues
version: 0.1.1
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  ffmpeg_kit_flutter: ^5.1.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
